### ISSUE TITLE
Comments from Code review June 14th

### ISSUE THREAD

**Issue by bwalsh** [ohsu-computational-biology/schemas#11]
## Phenotype qualifiers:
- why are they OR'd together?
- why are qualifiers an array?
## Features/Genotype
- Drop Regex in order to improve chances of PR merge
- Single external identifier lookup.
- Redirect /features/search to g2p for standalone use case (frontend change).
## genotypephenotype response
- return only feature ids

**Comment by david4096** [comment]
@bwalsh You've answered my questions regarding the qualifier array, namely, they can be both a measure of severity and other more specific qualifiers, thanks.

If strict matching can fit your use cases then sending _single_ qualifiers in a request and performing the filtering client-side might be a favorable approach, at least for simplicity of implementation. We want to make the interface understandable by limiting the complexity of the query.

Regarding the g2p response, I consider it good practice to not repeat the Feature or Phenotype documents entirely, especially if they have their own API. The reason is that the FPA has a unique ID, but there are no guarantees the phenotype or feature records they contain haven't changed, so the same ID might point to two objects.

That means to glean all the data from a g2p request one would have to perform requests against the phenotypes and features APIs respectively. It also suggests that a more generic evidence API is warranted.

A point we weren't able to get to in the call was the role of `environmentalContext`. I understand Evidence as "Paper X mentions phenotype Y and feature Z", however, the linkage to environmentalContext is less clear. Are these context's data gleaned from Paper X? Is this a tag on the phenotype?

Exposing your `CGD.ttl` as a feature set seems like a step in the right direction, however, to sensibly use it we'll need to make some changes to the SearchFeaturesRequest.

All in all, great work. This is really hard and we of course won't get it all right the first time! I want to make sure the data model is transparent enough so that although there is some SPARQL magic behind the scenes, we don't see it in the interface.
